Adding adoption by NASA
sourcemeta/awesome-jsonschema pull request #30
Opened 2024-05-09 07:44 UTC by Era-cell

2024-05-09 14:26 UTC, jviotti commented on data.yaml
> +- title: N.A.S.A
```suggestion
- title: NASA 
```

2024-05-09 14:26 UTC, jviotti commented on data.yaml
> +  summary: N.A.S.A adopts the GCN Unified Schema is a framework for defining GCN Notices expressed in JSON format using the JSON Schema
```suggestion
  summary: NASA adopts the GCN Unified Schema is a framework for defining GCN Notices expressed in JSON format using the JSON Schema
```

2024-05-09 14:27 UTC, jviotti commented on data.yaml
> +  summary: N.A.S.A adopts the GCN Unified Schema is a framework for defining GCN Notices expressed in JSON format using the JSON Schema
You should say "using JSON Schema" not "using the JSON Schema". The latter is incorrect

2024-05-09 14:28 UTC, jviotti commented on data.yaml
> +  summary: N.A.S.A adopts the GCN Unified Schema is a framework for defining GCN Notices expressed in JSON format using the JSON Schema
They don't "adopt" GCN. It is their project. You should say something like "NASA maintains the GCN Unified Schema, a set of JSON Schemas for crafting GCN notices"

2024-05-09 14:29 UTC, jviotti requested changes
I left some comments. Also, I think you forgot to run `npm start` as said on the contributing guide. Otherwise the README won't be re-generated

2024-05-09 15:00 UTC, Era-cell commented
> I left some comments. Also, I think you forgot to run `npm start` as said on the contributing guide. Otherwise the README won't be re-generated

I removed my latest commit and pushed in into remote. The PR which was open got closed. Reverting of the commit caused this

2024-05-09 15:23 UTC, Era-cell commented
> I left some comments. Also, I think you forgot to run `npm start` as said on the contributing guide. Otherwise the README won't be re-generated

Oh! I just pushed the yaml file. Guideline said - add directly to yaml and send a PR..  .

2024-05-09 15:26 UTC, jviotti commented
Feel free to clarify the contributing guide in another PR if you want!

2024-05-09 17:58 UTC, Era-cell commented
> Feel free to clarify the contributing guide in another PR if you want!

![Screenshot 2024-05-09 232756](https://github.com/sourcemeta/awesome-jsonschema/assets/77973415/718f5676-b78a-4de3-ba6b-afad7767f4f5)
Like this is fine?

2024-05-10 01:27 UTC, jviotti commented
Something like that. If you send a PR, I can drop suggestions there

2025-04-22 16:26 UTC, closed without merging